[tool.poetry]
name = "pykinect_azure"
version = "0.1.0"
description = ""
authors = ["Ibai Gorordo"]

[tool.poetry.dependencies]
python = "^3.9"
opencv-python = "^4.5.5"
numpy = "^1.22.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
